- op: replace
  path: /spec/rules/0/host
  value: qa.gpevn.com

- op: replace
  path: /spec/rules/0/http/paths/0/backend/service/name
  value: scg-asgn-be-active-qa

- op: add
  path: /metadata/annotations/cert-manager.io~1cluster-issuer
  value: letsencrypt-staging

- op: add
  path: /spec/tls
  value:
    - hosts:
        - qa.gpevn.com
      secretName: scg-asgn-tls
