apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: scg-asgn
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - env: dev
                  prune: true
                  selfHeal: true
                - env: qa
                  prune: true
                  selfHeal: true
                - env: staging
                  prune: true
                  selfHeal: false
                - env: prod
                  prune: false
                  selfHeal: false
          - list:
              elements:
                - svc: backend
                - svc: frontend
  template:
    metadata:
      name: 'scg-asgn-{{.svc}}-{{.env}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: scg-asgn
      source:
        repoURL: https://github.com/tridtaytech/scg-sre-assignment.git
        targetRevision: main
        path: 'project/scg-asgn/deployment/overlays/{{.env}}/{{.svc}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: 'app-{{.env}}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
  templatePatch: |
    spec:
      syncPolicy:
        automated:
          prune: {{ .prune }}
          selfHeal: {{ .selfHeal }}
