apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: scg-asgn
  namespace: argocd
spec:
  description: scg-asgn — frontend + backend across all envs
  sourceRepos:
    - https://github.com/<OWNER>/scg-sre-assignment.git
  destinations:
    - namespace: 'app-*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
