apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - configmap.yaml

commonLabels:
  app.kubernetes.io/name: scg-asgn-fe
  app.kubernetes.io/part-of: scg-asgn
