apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-qa
nameSuffix: -qa

resources:
  - ../../../base/backend

images:
  - name: backend:placeholder
    newName: public.ecr.aws/c5a3w2d1/backend
    newTag: PLACEHOLDER

replicas:
  - name: scg-asgn-be
    count: 2

patches:
  - path: disable-analysis.yaml
    target:
      kind: Rollout
      name: scg-asgn-be
