apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: scg-asgn-be-success-rate
spec:
  args:
    - name: service-name
  metrics:
    - name: success-rate
      interval: 30s
      count: 5
      successCondition: result[0] >= 0.95
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prom-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(http_server_requests_seconds_count{
              service="{{args.service-name}}", status!~"5.."
            }[2m]))
            /
            sum(rate(http_server_requests_seconds_count{
              service="{{args.service-name}}"
            }[2m]))
