apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rollout.yaml
  - service-active.yaml
  - service-preview.yaml
  - analysistemplate.yaml
  - configmap.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: scg-asgn-be
  app.kubernetes.io/part-of: scg-asgn
