# Teaches kustomize how to handle Argo Rollouts CRDs:
#  - rewrite name references when nameSuffix is applied
#  - allow `replicas:` transformer to target a Rollout
#  - apply commonLabels (and commonAnnotations) into Rollout selector + pod template

nameReference:
  - kind: Service
    fieldSpecs:
      - kind: Rollout
        group: argoproj.io
        path: spec/strategy/blueGreen/activeService
      - kind: Rollout
        group: argoproj.io
        path: spec/strategy/blueGreen/previewService
  - kind: AnalysisTemplate
    group: argoproj.io
    fieldSpecs:
      - kind: Rollout
        group: argoproj.io
        path: spec/strategy/blueGreen/prePromotionAnalysis/templates/templateName
      - kind: Rollout
        group: argoproj.io
        path: spec/strategy/blueGreen/postPromotionAnalysis/templates/templateName

replicas:
  - kind: Rollout
    group: argoproj.io
    path: spec/replicas
    create: true

commonLabels:
  - kind: Rollout
    group: argoproj.io
    path: spec/selector/matchLabels
    create: true
  - kind: Rollout
    group: argoproj.io
    path: spec/template/metadata/labels
    create: true

commonAnnotations:
  - kind: Rollout
    group: argoproj.io
    path: spec/template/metadata/annotations
    create: true
